language: java
jdk:
- oraclejdk7
#- oraclejdk8
#- oraclejdk6
#- openjdk7
#- openjdk6
env:
  global:
  # SONATYPE_USERNAME
  - secure: Z4Uog23iOIu1hig9Jo6EG1SNMlf9ccFwgCgRgwuzlJkUWIdSfmDTpC0zhEK4I6fstMwCYOn96ZmzjLqwRZac/6FBcxdmZYd2ZsNYTG8LrRTPYswxFLhSL8oVGD6Rrw+yo3r1nRPekFsbAmEVrSoxX6thkhtldEyve2J7OIQeJ7g=
  # SONATYPE_PASSWORD
  - secure: CGO0xjROQydae1Z1dYlkT/cE0pvPUdGv8mIZtOLR48P4Hb+E8WBjIhagDr3OYZEywDGdwVq2eZqQzbN5UGggCdnTmR1ntQCg8nfvK/PiaVrOXcm2fS+PB+PFuilwsNIibAVLZkGQMV+XudjvDAvTlq2Pp9X7geKKppxoRCAlPKc=
  # GPG_PASSPHRASE
  - secure: EWH1cxXUCH40iCgEzNCgCpgP0Ev+tSCJkXYou5a7A5jIF8+eJQhZsXen8nxiptgp1iTjRp8zN0mFNvYcQIIG/46/3jJuZ0/orz/jo9zYVawD2izDv50OKf868IwUCjagD1EvMTaCc9pu6UQJnNjcR90Zc6QHpH4Samlacxlw5hA=
  #- secure: qc1Z5SOx6+sq4huAy+MWywGtO9JHolbQg6zNU5RVH6KJIXSYB/JAsSh/yDnD8EZ6ybex/+z/1dWRRTvB9s/mmml02PQV5prr2Y1bcxYD5En6SRWFVHvwi+xU1LnqYJK5dKOh2+heDJpM5ojW1cyzJoFRfXQxDSQQ+icnnibqueI=
  # ENC_SECRET
  - secure: "epqcUfjdyWXf/iZ97672mJInkNEKWdPuo+6CZePb/YHuTIcNFrVctnMMkkzQz5GY9iybBc76qMpZEuVDWxaEEqn8vH5GyNJ67XkENhCHOft7RS49cKTmBOxfjjoFf3fsz1tGAfKbY7i0PJYkugmdb6tYeyjJzqvta13RGeIYZd8="
before_install:
- mkdir gpg
- openssl aes-256-cbc -k "$ENC_SECRET" -in secring.gog.enc -d -a -out gpg/secring.gog
- openssl aes-256-cbc -k "$ENC_SECRET" -in pubring.gpg.enc -d -a -out gpg/pubring.gpg